Token minting
FluxityStellar/fluxity-api pull request #1
Opened 2023-10-22 21:11 UTC by feritka79

Initial Project Folder Structure
Database Configuration and Token Mode
Creating the .env and .env.example Files
Installing the body-parser Package

2023-10-22 21:27 UTC, ceydae requested changes

2023-10-22 21:27 UTC, ceydae commented on src/index.ts
> +app.use(express.urlencoded({ extended: false }));
Change these to `bodyParser.json` and `bodyParser.urlencoded`

2023-10-22 21:27 UTC, ceydae commented on src/database/db.ts
> +const MONGO_URI = 'mongodb://localhost:27017/Fluxity';
use process.env and put it in env and env.example

2023-10-22 21:27 UTC, ceydae commented on src/database/db.ts
> +  }
Change the error text to something meaningful
exit the app

2023-10-22 21:27 UTC, ceydae commented on src/database/db.ts
move db.ts to src/ and remove database directory

2023-10-22 21:27 UTC, ceydae commented on src/index.ts
> +dotenv.config();
move this up, below the imports

2023-10-22 21:27 UTC, ceydae commented on src/index.ts
> +db();
pass process.env.DB_URL to this as an argument

2023-10-22 21:27 UTC, ceydae commented on src/index.ts
>  const port = 3000;
put it in env and env.example

2023-10-22 21:27 UTC, ceydae commented on src/models/tokens.ts
> +export default mongoose.model('Tokens', Tokens);
use Token instead of Tokens

2023-10-22 21:27 UTC, ceydae commented on src/index.ts
> +app.get('/', indexHandler);
move this to routes/index.ts

2023-10-22 23:06 UTC, feritka79 reviewed
fix

2023-10-22 23:08 UTC, ceydae requested changes
routes

2023-10-23 09:07 UTC, feritka79 reviewed
add router

2023-10-23 09:44 UTC, feritka79 reviewed
fix route index and add folder token (index, addToken)

2023-10-23 10:17 UTC, feritka79 reviewed
change import name

2023-10-23 10:17 UTC, ceydae approved these changes

2023-10-23 10:17 UTC, merged