feat: add swagger config , install package : swagger-jsdoc, swagger-u…
FluxityStellar/fluxity-api pull request #3
Opened 2023-10-27 15:03 UTC by feritka79

add swagger

2023-10-27 15:06 UTC, feritka79 commented
pleas check title and description .

2023-10-27 16:37 UTC, feritka79 reviewed
Fix

2023-10-27 23:16 UTC, feritka79 reviewed
add remove token api

2023-10-28 00:08 UTC, ceydae requested changes

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/token.ts
> + *                     example: Token Invalid ...
change content to: "Failed to save the token"

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/token.ts
> + *
Add a authorization field besides the body fields for this route.

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenMint.ts
> + *     summary: Mint token
Mints a new token and transfers the tokens to the specified destination address.

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenMint.ts
> + *     tags: [Apis]
change to "token"

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenMint.ts
> + *                 example : GBLBJBTC2URCWUTIXY42W7M5GAZ2NIKTS4QF77BHHWHSBKKSPS2DTOHA
change to contract-like address, starting with C

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenMint.ts
> + *         description:  Minted token
Token has been minted successfully

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenMint.ts
> + *         description: User minted
User has already minted the fake tokens

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenMint.ts
> + *
no need for authorization for this route.

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenMint.ts
move this file to /src/swagger/token/mint.ts

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
move this file to /src/swagger/token/delete.ts

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *     summary: Delete token
Deletes a token from the list of claimable tokens.

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *     tags: [Apis]
change tag to token

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *                 example : GBLBJBTC2URCWUTIXY42W7M5GAZ2NIKTS4QF77BHHWHSBKKSPS2DTOHA
chang example

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *         description: Deleted token
Token has been deleted successfully

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *                   example: Deleted token successful
change server response and this content to "Token deleted successfully"

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *         description: Token not exist
Token does not exist on the database

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *                   example: Token not exists
Change server response and this content to "Token does not exist"

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *       400:
change the server response's status code to 404

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *         description: Authorization
change to Authorization failed

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *                   example: Authorization not found
Authorization failed

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *                   example: Access not found
Authorization failed

2023-10-28 00:08 UTC, ceydae commented on src/routes/swagger/apis/tokenDelete.ts
> + *
add a header field for authorization for this route.

2023-10-28 10:12 UTC, feritka79 reviewed
fix

2023-10-28 18:31 UTC, ceydae commented on src/utils/token/removeToken.ts
This file is not needed. Remove it

2023-10-28 18:32 UTC, ceydae requested changes

2023-10-28 18:32 UTC, ceydae commented on src/utils/token/removeToken.ts
> +export default removeToken;
Remove the whole file

2023-10-28 19:10 UTC, ceydae approved these changes

2023-10-28 19:11 UTC, merged