Email subscription
FluxityStellar/fluxity-api pull request #4
Opened 2023-10-27 19:45 UTC by omikay

2023-10-28 00:31 UTC, ceydae requested changes

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +import { Request, Response } from 'express';
add a blank line between package imports and local imports

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/index.ts
This is an empty file, not containing anything and therefore the code doesn't run.

2023-10-28 00:31 UTC, ceydae commented on src/utils/validateEmail.ts
> +export function validateEmail(email: string): boolean {
change this function to an arrow function
use `export default` when there's only 1 thing to export.
use inline return `() => return_value` and remove the variable and use it in place

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +        const { email } = req.body;
lowercase the email here (before checking it with existing emails in db since they all are lowercased)

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +        res.status(500).json({ message: "Error adding subscriber", error });
Use the ResponseTemplateType to response values.

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +        res.status(201).json(savedSubscriber);
Use the ResponseTemplateType to response values.

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +        res.status(201).json(savedSubscriber);
Return the `res.status...` so that the function always returns in any circumstances

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +        res.status(500).json({ message: "Error adding subscriber", error });
Return the `res.status...` so that the function always returns in any circumstances

2023-10-28 00:31 UTC, ceydae commented on src/models/Subscriber.ts
> +    }
remove this field and add a timestamps: true to the config of the model. 

https://mongoosejs.com/docs/timestamps.html

2023-10-28 00:31 UTC, ceydae commented on src/models/Subscriber.ts
> +const subscriberSchema: Schema = new Schema({
no need to specify the type when the type can be inferred

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/getSubscribers.ts
> +import Subscriber from '../../models/Subscriber';
add a blank line between package imports and local imports

2023-10-28 00:31 UTC, ceydae commented on src/routes/subscribe/getSubscribers.ts
> +    }
use ResponseTemplateType for responses and return the responses

2023-10-28 12:20 UTC, omikay commented on src/routes/subscribe/index.ts
I don't know why it happened, but it's resolved now.

2023-10-28 19:41 UTC, ceydae requested changes

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +import responseTemplate from '../../utils/responseTemplate';
You do not need to import and use this function. Just make sure that all responses are following ResponseTemplateType's structure. No import needed.

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +import { validateEmail } from '../../utils/validateEmail';
Default export does not need {} in import name

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +        const { email } = req.body.toLowerCase();
This doesn't work. Make sure the email is received from req.body and then lowerCase it in another variable.

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +                responseTemplate({
No need to use this function here

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/index.ts
> +router.post('/add-subscriber', addSubscriber);
Change this to / (The overall URL will be `/subscribe/`)

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/index.ts
> +router.get('/get-subscribers', getSubscribers);
Change this to / (The overall URL will be `/subscribe/`)

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/getSubscribers.ts
rename this file to get.ts

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
rename this file to add.ts

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/getSubscribers.ts
> +import responseTemplate from '../../utils/responseTemplate';
You do not need to import and use this function. Just make sure that all responses are following ResponseTemplateType's structure. No import needed.

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/getSubscribers.ts
> +            responseTemplate({
Do not use this function here. Just pass the object to the json() function

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/getSubscribers.ts
> +                message: 'Unble to fetch subscribers',
Use `error.message` for message

2023-10-28 19:41 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
> +                message: 'Error adding subscriber',
Use `error.message` for message

2023-10-29 05:21 UTC, omikay commented on src/routes/subscribe/addSubscriber.ts
Why? : D

2023-10-29 07:17 UTC, ceydae commented on src/routes/subscribe/addSubscriber.ts
`addSubscriber.ts` file is inside the `subscribe` folder. So we can remove the word `subscriber` from the name it is still clears that this file is related to `subscribers` (because of the directory name). But if we don't remove it, we have duplicated names, both in directory and the file name.

2023-10-30 18:48 UTC, ceydae requested changes
Prettier config is added but the files in this PR doesn't use them. Enable prettier and save these files again.

2023-10-30 18:48 UTC, ceydae commented on src/routes/subscribe/add.ts
> +        const email = eAddress.toLowerCase();
change this so `req.body` would have a field called `email` 
and rename email to eAddress

2023-11-01 11:22 UTC, ceydae requested changes

2023-11-01 11:22 UTC, ceydae commented on src/routes/subscribe/add.ts
> +    const existingSubscriber = await Subscriber.findOne({ eAddress });
change eAddress to email: eAddress

2023-11-01 11:22 UTC, ceydae commented on src/routes/subscribe/add.ts
> +    const newSubscriber = new Subscriber({ eAddress });
change eAddress to email: eAddress

2023-11-01 11:22 UTC, ceydae commented on src/routes/subscribe/add.ts
> +    return res.status(200).json({
change status code to 201

2023-11-01 15:47 UTC, ceydae approved these changes

2023-11-01 16:11 UTC, merged