chore: change url server swagger
FluxityStellar/fluxity-api pull request #6
Opened 2023-10-28 20:43 UTC by feritka79

change server url swagger

2023-10-28 20:45 UTC, feritka79 reviewed
fix

2023-10-29 07:15 UTC, ceydae requested changes

2023-10-29 07:15 UTC, ceydae commented on src/routes/swagger/configSwagger.ts
>        ],
add both localhost and api.fluxity in the servers array

2023-10-29 12:17 UTC, ceydae approved these changes

2023-10-29 12:17 UTC, merged