Restructure claim token API
FluxityStellar/fluxity-api pull request #7
Opened 2023-10-29 20:45 UTC by feritka79

restructure

2023-10-30 06:04 UTC, feritka79 reviewed
Reviewed all comment

2023-10-30 19:03 UTC, ceydae requested changes
Enforce the use of IResponseTemplate for all routes.
Change the PR title and description

2023-10-30 19:08 UTC, ceydae requested changes

2023-10-30 19:08 UTC, ceydae commented on src/routes/token/add.ts
> +    return res.status(200).json({
use 201 whenever something is being created.

2023-10-31 21:00 UTC, ceydae requested changes

2023-10-31 21:00 UTC, ceydae commented on src/swagger/token/get.ts
> + *     summary: Receives tokens from the list of claimable tokens.
Returns the list of the claimable tokens

2023-11-01 11:19 UTC, ceydae approved these changes

2023-11-01 11:32 UTC, merged